### ISSUE TITLE
Chapter 01. 데이터베이스 기본 개념

### ISSUE THREAD

**Issue by new-pow** [CodeSquad-2023-BE-Study/DB-Study#1]
- 책을 읽으며 질문을 남겨주세요.

**Comment by crtEvent** [comment]
교재 27p(PDF 25p)
> 내용과 함께 설명된 데이터 구조를 스키마schema라고도 하지만 메타 데이터metadata라고도 한다

## 궁금한 점
- 개발 공부하다 보면 메타 데이터라는 말 한번씩 듣게 되는데 조금 헷갈렸습니다. 스키마 = 메타 데이터 인지?

**Comment by crtEvent** [comment]
## 찾아 본 것
- 인터넷에 메타 데이터 검색하면 '데이터에 관한 구조화된 데이터', '데이터에 대한 데이터', '데이터를 설명해 주는 데이터'라고 하고
- 스키마는 '데이터베이스의 구조와 제약조건에 관해 전반적인 명세를 기술한 것', 'DB의 구조와 제약 조건에 관한 전반적인 명세를 정의한 메타데이터의 집합'이라고 하네요.
- 스키마가 메타 데이터의 일종이구나 라고 생각했습니다.
- 스키마='명세를 기술한 것?' 어디에 어떤 형태로 기술되어 있는지도 궁금한데 이번 챕터 내용과는 관련 없는 듯

**Comment by crtEvent** [comment]
교재 30p(PDF 28p)

## 궁금한 점
- 우리가 쓰고 있는 MySQ에서 범주형 데이터(Categorycal data)와 수치형 데이터(Numerical data)를 제약 조건으로 구별할 수 있는지 궁금했어요.

- 예를 들어 처음엔 학년 속성은 숫자 데이터라고 생각했어요.
- 그런데, 학년은 범주형 데이터(Categorycal data)라서 범위(1~4학년)가 있어야 하고, 연산(1학년 + 3학년 = 4학년?)이 의미 없어서 int 타입이면서도 범위와 연산을 제한할 방법이 있는 건가?


## 찾아 본 것
### MySQL의 Enum 타입
- MySQL 데이터 타입에도 Enum 타입이 있네요. Enum 타입으로 컬럼에 들어올 값을 제한할 수 있습니다.
- 대신 문자열로 저장됩니다.
- ENUM 타입으로 설정할 경우 테이블 변경이 어려워 사용하지 말자는 주장도 있습니다
    - [MySQL의 ENUM 타입을 사용하지 말아야 할 8가지 이유](https://velog.io/@leejh3224/%EB%B2%88%EC%97%AD-MySQL%EC%9D%98-ENUM-%ED%83%80%EC%9E%85%EC%9D%84-%EC%82%AC%EC%9A%A9%ED%95%98%EC%A7%80-%EB%A7%90%EC%95%84%EC%95%BC-%ED%95%A0-8%EA%B0%80%EC%A7%80-%EC%9D%B4%EC%9C%A0)
```SQL
CREATE TABLE students (
  id INT PRIMARY KEY,
  name VARCHAR(50),
  grade ENUM('1', '2', '3', '4')
);
```

### CHECK 제약 조건
- CHECK 제약 조건으로 INT형 컬럼에 들어올 값도 제한할 수 있어요
- 다만 연산을 제한할 방법은 없는 듯 합니다.
```SQL
CREATE TABLE students (
  id INT PRIMARY KEY,
  name VARCHAR(50),
  grade INT CHECK (grade >= 1 AND grade <= 4)
);
```

**Comment by crtEvent** [comment]
책 31p(PDF 29p)
> 좀 더 다양한 기준의 데이터 분류 방법이 있지만 데이터베이스에 첫발을 내딛은 지금은 이번 장에서 설명한 데이터 분류 방법만 이해해도 충분하다

## 궁금한 점
- 다양한 기준의 데이터 분류 방법들

## 찾아 본 것
- 데이터를 수집/응용하는 사람들이 분류하기 나름인 듯
- [빅데이터의 데이터 유형 및 구조 분류체계](https://www.cisp.or.kr/archives/22015)

**Comment by leegyeongwhan** [comment]
책 26

## 궁금한 점
- 시장조사기관 IDC의 전망에 따르면 기업에 존재하는 데이터의 80%는 구조화되지 않은 비정형 데이터라고 하는데
현실 세계에서 방대한 비정형 데이터를 다루는 방법에대해 궁금증이 생겼습니다.

- 오디오같은 데이터는  어떤식으로 관리할지 궁금해졌습니다.
## 찾아 본 것
- 비정형데이터는 우리가 일상적으로 사용하는 자연어 텍스트 데이거 대표적이고 이런 데이터는 자연어 데이터라고 한다고 합니다.  호눅스 수업에 들었던 일락스트릭 서치 에대한 궁금증이 더생기네요

-  오디오 데이터는 아직 제수준에서는 이해하기 어렵네요.
스터디원들과 추후 가볍게 생각해보고싶습니다.

**Comment by new-pow** [comment]
책 28pg
---
## 궁금했던 것
- 파일 시스템과 데이터베이스의 차이점
  - 비정형 데이터는 파일시스템으로 저장해야하지 않을까 싶어서 찾아보기 시작했다.
- 비정형데이터란 무엇인가? 어떻게 저장되는가?

## 찾아본 것
- 데이터베이스는 파일시스템의 문제점을 보완하고자 나온 시스템인 것 같다. [참고링크](http://jidum.com/jidums/view.do?jidumId=78)
- 비정형데이터가 어떻게 저장되는지에 대해서 저도 궁금해서 좀 찾아봤습니다. [참고링크](https://www.tibco.com/ko/reference-center/what-is-unstructured-data)
    - 관리하기 쉬운 형식으로 변환합니다. (XML 등)
    - CAS 시스템이 사용됩니다. (컨텐츠 주소 지정 가능 스토리지 Content Addressable Storage)
    - 저장시스템으로 BLOB 을 사용하기도 합니다. (Binary Large Object)

**Comment by new-pow** [comment]
아직은 개념 정리 단계라 크게 궁금한 부분은 없었습니다.
잘 정리된 글이 있어서 공유합니다. [링크](http://jidum.com/jidums/view.do?jidumId=78)

**Comment by new-pow** [comment]
이것 저것 찾다보니 `데이터베이스 파일 시스템` 에 대한 글을 좀 읽었는데 재밌네요!
메타데이터를 통해 기존의 계층형 파일트리가 아닌 다른 방식으로 파일을 탐색하고 접근할 수 있도록 하는 시스템입니다.
애플의 spotlight 가 이런 파일시스템을 가지지 않나 ㅎㅎ 추측이지만 관련된 아티클 찾은 것을 공유합니다.

- [애플 spotlight 위키피디아](https://en.wikipedia.org/wiki/Spotlight_(Apple))
- [Apple Pro Training Series: OS X Lion Support Essentials: Supporting and Troubleshooting OS X Lion: Data Management](https://www.peachpit.com/articles/article.aspx?p=1762250)

> Spotlight는 각 로컬 볼륨에 대해 인덱싱된 메타데이터의 고도로 최적화된 데이터베이스를 유지하기 위해 백그라운드에서 작동하기 때문에 광범위하고 심층적인 검색을 신속하게 수행할 수 있습니다. Lion을 처음 설정하면 사용 가능한 모든 로컬 볼륨을 인덱싱하여 이러한 데이터베이스를 생성합니다. 시스템은 또한 새 로컬 볼륨이 처음 연결될 때 인덱싱합니다.
>
> Mac에서 메타데이터 서버의 줄임말인 mds 라는 백그라운드 프로세스 는 파일 시스템 전체에서 변경 사항이 있을 때 인덱스 데이터베이스를 즉시 자동으로 업데이트합니다. 이러한 인덱스는 최신 상태로 유지되기 때문에 Spotlight 프로세스는 전체 결과를 반환하기 위해 데이터베이스를 검색하기만 하면 됩니다. 본질적으로 Spotlight는 백그라운드에서 모든 것을 선제적으로 검색하므로 필요할 때 결과를 기다릴 필요가 없습니다.

- [Explanation of Database File Systems
](http://akaimbatman.blogspot.com/2005/06/explanation-of-database-file-systems.html)

**Comment by jinny-l** [comment]
듀이:
- 오디오 데이터를 이미지를 학습시킬 수도 있고
- 알고리즘에 의해 주파에 따라 분석할 수도 있음

**Comment by jinny-l** [comment]
오디오 파일은 어떻게 저장될까?

**Comment by crtEvent** [comment]
## 파일 시스템

- 계속 진화 중 ㅎ
- 전통적인 방식: 파일의 위치를 저장하는 방식
